--- 
title: "Bayesian Finance: Modeling Earnings for S&P 500 Companies"
author: "Nicholas Di, Nolan Meyer, Duc Ngo"
date: "Macalester College, Fall 2021, STAT 454 Capstone Project"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
#github-repo: openscapes/series
description: "Bayesian Statistics Capstone Project"
---

# Welcome {#welcome}

## Introduction

Welcome to our STAT 454: Bayesian Statistics capstone project. We all have an interest in and connections to the financial world, whether that be through our majors or internships, which led us toward this project. Financial information, like stock market prices, are known to be notoriously hard to predict. We wanted to take a Bayesian approach to try and tackle a similar situation: predicting the future earnings of S&P 500 companies. In this project we seek to model future earnings using other financial information about a company, like previous earnings and sales. We explore a few Bayesian hierarchical models, as well as a bayesforcast model to try and identify one that can provide insight and better predictions for future company's earnings. 

