# Reflection {#reflection}

## Next Steps

We would love to have more time to explore SARIMA models in bayesforecast, as well as improve our hierarchical models as well. With bayesforcast, this was a new package to us which took some time to learn, and there's still more to explore that we weren't able to get to. For our hierarchical models, they had some troubles dealing with outliers and the volatility of the financial world. We would like to explore more models in the future, possibly with more or different predictors, however these models took hours to run and a time constraint limited the amount of models we could try. Future models could become more accurate at predicting future earnings for companies.

## Acknowledgements

For our project, we want to thank Dr. Alicia Johnson for teaching us a lot of useful knowledge about Bayesian Statistics. Moreover, Dr. Alicia Johnson has given us a ton of feedback, and helped us through all the difficulties we have encountered. It has been a challenging project and we would not have been able to do it without the tools and techniques she taught us throughout this semester.

## Citations

“4.1 Seasonal Arima Models: Stat 510.” PennState: Statistics Online Courses, https://online.stat.psu.edu/stat510/lesson/4/4.1. 

“Bayesian Time Series Modeling with Stan [R Package Bayesforecast Version 1.0.1].” The Comprehensive R Archive Network, Comprehensive R Archive Network (CRAN), 17 June 2021, https://cran.r-project.org/web/packages/bayesforecast/index.html.


“Forecasting: Principles and Practice (2nd Ed).” 8.9 Seasonal ARIMA Models, https://otexts.com/fpp2/seasonal-arima.html. 

Modeling Multiple Times Series with Applications - USGS. https://rmgsc.cr.usgs.gov/outgoing/threshold_articles/Tiao_Box1981.pdf. 

“Modeltime Integration.” Bayesmodels, https://albertoalmuinha.github.io/bayesmodels/articles/modeltime-integration.html. 

*S&P 500 Companies - S&P 500 Index Components by Market Cap*, https://www.slickcharts.com/sp500

“Yahoo Finance - Stock Market Live, Quotes, Business &amp; Finance News.” Yahoo! Finance, Yahoo!, https://finance.yahoo.com/. 

## Code Appendix

To reproduce these results, the complete files and data sets are provided below:

[Google Drive Link](https://drive.google.com/drive/folders/1O367Giuc7U2HH_IIk2R1i5cnu80ezRcK?usp=sharing)

